version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sidside/kittygram_backend
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/backend_static/static/
    depends_on:
      - db
  frontend:
    image: sidside/kittygram_frontend
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sidside/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media/
    ports:
      - 9000:80
